name: Notification Workflow

on:
  schedule:
    # This schedule runs the job every minute.
    - cron: '*/1 * * * *'

jobs:
  send_notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin  # Install Firebase Admin SDK

      - name: Run notification script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          python send_notification.py
